# Generated by Django 2.0.4 on 2018-04-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='media/studentsAvatar/None/no-img.jpg', upload_to='media/studentsAvatar/'),
        ),
    ]
