# Generated by Django 2.0.4 on 2018-04-17 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180417_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='studentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Student'),
        ),
        migrations.AlterField(
            model_name='score',
            name='subjID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Subject'),
        ),
    ]
