# Generated by Django 2.0.4 on 2018-04-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180417_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(help_text='Enter student ID', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectID',
            field=models.CharField(help_text='Enter subject ID', max_length=10, unique=True),
        ),
    ]
