# Generated by Django 2.0.4 on 2018-04-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180419_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(upload_to='studentsAvatar'),
        ),
    ]
